### ISSUE TITLE
Why? Just for fun?

### ISSUE THREAD

**Issue by vitiral** [martin-eden/Lua-Itness#1]
I'm having a hard time seeing why someone would use this library. Was it just a fun project? If so, awesome!

However, I don't think I would ever use

```
    ( a ( b ) ( c ( d ) ) )
```

vs
```
    { 'a', { 'b' }, { 'c', { 'd' } } }
```

Considering the latter can also use all of Lua's features.

**Comment by martin-eden** [comment]
I'm going to use it for my data codecs. Maybe will start from [CSV](https://github.com/martin-eden/workshop/tree/master/concepts/csv) or [JSON](https://github.com/martin-eden/workshop/tree/master/concepts/json) codec, then [pkzip](https://github.com/martin-eden/workshop/tree/master/concepts/pkzip).

As [I said in lua-l maillist](https://groups.google.com/g/lua-l/c/v_wHN6CBvGk/m/wcqSx1zTAQAJ), I admire Lua table syntax but consider using source code to store data as tool misuse.

If you store data as Lua code returning tables, it looks fun and easy. But you need Lua to actually execute code (even if it looks like table definition). And stock Lua doesn't have neither table parser nor serializer, so you will need some. (You may take  serializer from this repo tho).

Imagine some WebAPI decided to switch from JSON to Lua tables syntax. It's asking for trouble, as any domestic hacker will try to insert Lua code to web requests:
```Lua
  SendDisplayTreeRequest("{ 'a', { 'b' }, { 'c', { 'd' } }, (function() print ('Hey there!') end)(), }")
```

**Comment by vitiral** [comment]
It's pretty easy to sandbox Lua and then read the globals as a data format, i.e. https://github.com/civboot/civlua/blob/main/lib/pkg/pkglib.lua#L72

```
M.ENV = {
  UNAME=UNAME,   LIB_EXT=M.LIB_EXT,
  format=string.format,
  insert=table.insert, sort=table.sort, concat=table.concat,
  pairs=pairs,   ipairs=ipairs,
  error=error,   assert=assert,
}; M.ENV.__index = M.ENV

  local env = setmetatable({}, M.ENV)
  local pkg, err = loadfile(path, nil, env)
```

With the above the executed code can't use `print` or anything else you didn't specify explicitly.

I've made a config language using this approach with a few more extensions [docs](https://htmlpreview.github.io/?https://github.com/civboot/civlua/main/lib/luck/README.html), [code](https://github.com/civboot/civlua/tree/main/lib/luck)

**Comment by martin-eden** [comment]
You are still executing code.

You can deprive code from input or output but you still need to execute it.

This can take arbitrary large time or memory.

```Lua
  local pkg, err = loadfile(path, nil, env)
  if not pkg then loaderr(name, path, err) end
  pkg()
```

**Comment by vitiral** [comment]
Yes, it doesn't work for non-trusted inputs. You can do hacks like limit the execution time/etc -- but it's still a hack.

What is your use-case? I've written a few serialization formats for civlua, I'd be interested in whether they could work for you (not saying you would use them, just curious if they meet your needs)

* [tv](https://github.com/civboot/civlua/tree/main/lib/tv) better and more specified csv
* [lson](https://github.com/civboot/civlua/tree/main/lib/lson) more readable json
* and then of course luck (linked above)

**Comment by martin-eden** [comment]
At first I wrote Lua tables serializer. And thus Lua became standard format for saving state.

From formats I did [TSV](https://github.com/martin-eden/workshop/tree/master/concepts/tsv), [CSV](https://github.com/martin-eden/workshop/tree/master/concepts/csv), [JSON](https://github.com/martin-eden/workshop/tree/master/concepts/json), [Torrent](https://github.com/martin-eden/workshop/tree/master/concepts/bencoding), [ZIP](https://github.com/martin-eden/workshop/tree/master/concepts/pkzip) codecs and [Lua source code](https://github.com/martin-eden/workshop/tree/master/concepts/lua) parser. Plus some binary formats from embedded electronics world like [RTC DS3231](https://github.com/martin-eden/workshop/tree/master/concepts/rtc_ds3231) and [Firmata](https://github.com/martin-eden/workshop/tree/master/concepts/firmata) protocol. All implementations produce Lua table.

With this codec I can just convert between Lua tables and Itness. I don't even need to change that parsers, just add step for converting result table.

**Comment by vitiral** [comment]
So you're saying it's an intermediate representation of other data serialization formats?

**Comment by martin-eden** [comment]
I didn't get what you are meaning under "intermediate representation".

Under "intermediate representation" I assume preprocessed data in memory with task-specific changes.

In this repo you may see "intermediate representation" in the result that [Sequencer.TableToSeq](https://github.com/martin-eden/Lua-Itness/blob/master/Sequencer/TableToSeq.lua#L132-L133) returns. It iterates over key-values and adds them to result list table. Value is wrapped in table. So for `{ a = 'A' }` it will return `{ [1] = 'a', [2] = { [1] = 'A' } }`. Then this result table is passed to serializer which writes to output string like `( a (A) )`. And this processing chain is reversed for deserializer.

Note that serializer writes to output, not returns string. (I've practiced "all data is string" approach a lot and is sick of it.)

([Input/output](https://github.com/martin-eden/Lua-Itness/tree/master/workshop/concepts/StreamIo) are separate classes. Input reads N bytes and returns string, output writes string. So input or output implementation can be pipe, string or file. Their users doesn't care.)

To your question. It's codec (coder-decoder, or serde if you prefer). Looking from outside it reads data in some format from input and writes data in some other format to output. From inside, if you have suitable Lua table you can preprocess it (TableToSeq) to another Lua table and pass that table to encoder. Or you can run decoder, get some Lua table and postprocess it (SeqToTable) to sane Lua table.

**Comment by vitiral** [comment]
I'm curious your thoughts for the (recently added) [lib/ds/ds/pod.lua](https://github.com/civboot/civlua/blob/main/lib/ds/ds/pod.lua). I've added support for them in both tv and lson (see links above)

This is the approach I've been wanting to do for a long time to add serialization to semi-arbitrary types in Lua.

**Comment by martin-eden** [comment]
Design is good. (Functions in table, keys are computed at runtime.)

Code style and naming are immature. (Multi-statement lines, wtf is "ds" (data structures I guess), doing `t.f = ...; f = t.f` instead of `f = ...; t.f = f`.)

But more important, you're doing your framework and doing it in a modular way. 3-5 years and you'll be fine.

But we are off-topic now.

**Comment by martin-eden** [comment]
Resolving by response timeout.
