### ISSUE TITLE
all in one (amalgamation) version 

### ISSUE THREAD

**Issue by denisdemaisbr** [martin-eden/Lua-Itness#2]
thx for app/script;

did you make a  'all in one' version to simplify (I'm using an OS without filesystem)

**Comment by martin-eden** [comment]
Nope, not yet.

I was thinking about packing distributions (like Love games) but hasn't implemented such functionality yet.

Currently I'm having fun writing heap manager on Arduino. After this maybe I'll do packer for my Lua projects. And will pack this repo first.

**Comment by martin-eden** [comment]
Hey Denis, I've done amalgamator (melder). https://github.com/martin-eden/lua_code_melder
